In [13]:
#question 1 
import numpy as np
A = np.array([[-6, 2 ,1 ,2 ,1],
[3 ,8 ,-4 ,1 ,0],
[-1, 1, 4 ,10, 1],
[3, -4, 1, 9, 2],
[2, 0 ,1 ,3, 10]])

print(A)
for i in range(len(A[0])):
    row_sum = 0.0
    for j in range(len(A[0])):
        if i != j:
            row_sum += abs(A[i][j])
    if abs(A[i][i]) <= row_sum :
        print("not diagonally dominant, on row number",i+1)
        break
    else:
        i = i + 1

B=np.array([[18, 3 ,6, -3],
[9, 13, -5 ,2],
[-3 ,-2, 4, 9],
[6 ,0 ,11, 3]])

list1 = []
print(B)
for i in range(len(B[0])):
    row_sum = 0.0
    for j in range(len(B[0])):
        if i != j:
            row_sum += abs(B[i][j])

    if abs(B[i][i]) >= row_sum :
        i = i + 1
        list1.append(i)
    else:
        print("not diagonally dominant, on row number",i+1)
        break
if len(list1) == len(B[0]):
    print("diagonally dominant")


[[-6  2  1  2  1]
 [ 3  8 -4  1  0]
 [-1  1  4 10  1]
 [ 3 -4  1  9  2]
 [ 2  0  1  3 10]]
not diagonally dominant, on row number 1
[[18  3  6 -3]
 [ 9 13 -5  2]
 [-3 -2  4  9]
 [ 6  0 11  3]]
not diagonally dominant, on row number 2
[1]


In [25]:
#question 2 : gauss siedel method 
import numpy as np
a =np.array([[-6 ,2 ,1 ,2 ,1],
[3 ,8 ,-4 ,1, 0],
[-1 ,1, 4 ,10 ,1],
[3 ,-4 ,1 ,9 ,2],
[2 ,0 ,1 ,3, 10]])

#checking for diagonal dominance
for i in range(len(A[0])):
    row_sum = 0.0
    for j in range(len(A[0])):
        if i != j:
            row_sum += abs(A[i][j])

    if abs(A[i][i]) >= row_sum :
        i = i + 1
    else:
        print("not diagonally dominant, on row number",i+1)
        break
        

b = np.array([3, 4, -2, 12,1])

# #need to create a matrix with 5 random elements. 
# soln = np.random.rand(len(b))

# for n in range(10000):
#     soln_old = np.copy(soln)
#     for i in range(len(b)):
#         soln[i] = b[i] 
#         for j in range(len(b)):
#             if i != j:
#                 soln[i] -= a[i][j]*soln[j]
    
#         soln[i] = soln[i]/(A[i][i])
#         i = i + 1
        
#     if np.linalg.norm(soln - soln_old, ord=np.inf) < 0.0000001:
#         print(f"Converged after {n+1} iterations")
#         break
#     n = n+1
    


for n in range(10000):
    soln_old = np.copy(soln)
    for i in range(len(b)):
        soln[i] = b[i]
        for j in range(len(b)):
            if i != j:
                soln[i] -= a[i][j]*soln[j]
        
        soln[i] = soln[i]/A[i,i]

    if np.linalg.norm(soln - soln_old, ord=np.inf) < 0.:
        break

print(soln)

not diagonally dominant, on row number 3
[-1.1222592  -1.3890687  -4.24606829  1.49505402  0.30054246]


In [1]:
#question 3 - gauss elimination 
import numpy as np
Z = np.array([[2 ,3, -2],
[1, 6 ,-4],
[4 ,-1 ,6]], dtype=float)

Y =  np.array([ 2 ,4 ,6])

p = len(Y)

for n in range(p-1): 
    for i in range(n+1,p): 
        factor = Z[i][n] / Z[n][n]
        Y[i] = Y[i] - factor * Y[n]
        for j in range(n,p):
            Z[i][j] = Z[i][j] - factor * Z[n][j]

print(Z)
# print(Y)

#back substitution

x = np.zeros(p)
for i in range(p-1, -1, -1):  # Start from the last row
    x[i] = (Y[i] - np.dot(Z[i, i+1:], x[i+1:])) / Z[i][i]

print("Solution vector x:")
print(x)

[[ 2.          3.         -2.        ]
 [ 0.          4.5        -3.        ]
 [ 0.          0.          5.33333333]]
Solution vector x:
[0.         1.41666667 1.125     ]


In [2]:
import numpy as np
from sympy import Symbol, Eq, solve, Matrix
A =np.array([[1, 2, 3],
[2 ,2 ,-2],
[3 ,-2 ,1]])

def det(A):
    if len(A) == 1:
        return A[0, 0]
    if len(A) == 2:
        return A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
    determinant = 0
    for i in range(len(A[0])):
        cofactor = A[0, i] * (-1) ** i
        submatrix = np.delete(np.delete(A, 0, axis=0), i, axis=1) 
        determinant += cofactor * det(submatrix)
    return determinant

def eigenvalues(A):
    x = Symbol('x')
    identity = np.eye(A.shape[0])
    A = A - x * identity
    dett = det(A)
    eigenvalues = solve(Eq(dett, 0), x)
    return eigenvalues

print(eigenvalues(A))

[-3.46410161513775, 3.46410161513775, 4.00000000000000]


In [69]:
import numpy as np
a =np.array([[1, 2, 3],
[2 ,2 ,-2],
[3 ,-2 ,1]])

b = np.array([ 2 ,4 ,6])

n = len(a)

def operation(A,i,j,k):
    A[i] = A[i] + k*A[j]
    return A

for j in range(n):
    for i in range(j+1,n):
        t = a[i,j]/a[j,j]
        operation(a,i,j,-t)
        operation(b,i,j,-t)

soln = np.zeros(n)
for i in range(n):
    term = 0.0
    for j in range(n):
        if j != i :
            term = term - a[n-i-1,j]*soln[j]
        
    soln[n-1-i] += (term + b[n-1-i])/a[n-1-i,n-1-i]
    
print(np.linalg.det(a))
print(np.linalg.solve(a,b))
print(a)
print(soln)

-48.00000000000001
[ 2. -0.  0.]
[[ 1  2  3]
 [ 0 -2 -8]
 [ 0  0 24]]
[2. 0. 0.]
